# Visit https://github.com/lowlighter/metrics#-documentation for full reference
# Configurator here: https://metrics.lecoq.io/embed
name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  # Your GitHub token
                  # The following scopes are required:
                  #  - public_access (default scope)
                  # The following additional scopes may be required:
                  #  - read:org      (for organization related metrics)
                  #  - read:user     (for user related data)
                  #  - read:packages (for some packages related data)
                  #  - repo          (optional, if you want to include private repositories)
                  token: ${{ secrets.METRICS_TOKEN }}
                  filename: Metrics/Metrics.svg

                  # Options
                  template: classic
                  base: header, activity, community, repositories, metadata
                  config_timezone: America/New_York
                  plugin_calendar: yes
                  plugin_calendar_limit: 0
                  plugin_habits: yes
                  plugin_habits_charts: yes
                  plugin_habits_charts_type: classic
                  plugin_habits_days: 5000
                  plugin_habits_facts: no # change this if configrator website is back up and running
                  plugin_habits_from: 2000
                  plugin_habits_languages_limit: 8
                  plugin_habits_languages_threshold: 0%
                  plugin_lines: yes
                  plugin_lines_delay: 300
                  plugin_lines_history_limit: 10
                  plugin_lines_repositories_limit: 20
                  plugin_lines_sections: base
